--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-26-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "C##JOO"."PRODUCT" 
   (	"PRODUCT_NO" NUMBER, 
	"STORE_NAME" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_PRICE" NUMBER, 
	"IMAGE_URL" VARCHAR2(300 BYTE), 
	"LINKED" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##JOO"."PRODUCT"."PRODUCT_NO" IS '상품번호';
   COMMENT ON COLUMN "C##JOO"."PRODUCT"."STORE_NAME" IS '편의점 이름';
   COMMENT ON COLUMN "C##JOO"."PRODUCT"."PRODUCT_NAME" IS '상품 이름';
   COMMENT ON COLUMN "C##JOO"."PRODUCT"."PRODUCT_PRICE" IS '상품 가격';
   COMMENT ON COLUMN "C##JOO"."PRODUCT"."IMAGE_URL" IS '상품 사진';
   COMMENT ON COLUMN "C##JOO"."PRODUCT"."LINKED" IS '상품 정보';
